export const site = {
  name: "Marty Smithson",
  title:
    "Marty Smithson — Marketing Analytics & Measurement Lead — Meridian MMM, incrementality, cash MER, executive BI — $25M+ paid mix.",
  description:
    "Marketing Analytics & Measurement Lead. Marketing science with Google Meridian MMM, incrementality (geo holdout, RCT, and test-and-learn), attribution, and cash MER versus platform ROAS. $25M+ in career-managed ad spend. GTM analytics from the Black Clover warehouse to an executive and partner portal — Snowflake and SQL. Head of BI & Performance Marketing at Black Clover. McFly Ads consulting practice: marketing science and media measurement for named brands. Mcfly Analytics Shopify App LIVE.",
  spendHeadline: "$25M+ in career-managed ad spend",
  url: "https://marty-smithson.pages.dev",
  revised: "2026-09-23",
  email: "martysmithson04@gmail.com",
  linkedin: "https://www.linkedin.com/in/marty-smithson",
  linkedinLabel: "linkedin.com/in/marty-smithson",
  phone: "801-717-0418",
  location: "American Fork, Utah",
  locationLine: "American Fork, Utah. Central Utah or US remote.",
  authorization: "US citizen. No visa sponsorship required.",
  mcfly: "https://mcflyads.com",
  mcflyDemo: "https://mcflyads.com/demo",
  mcflyProduct: "Mcfly Analytics Shopify App",
  mcflyTitle: "Founder and Data Analytics Consultant",
  education:
    "Bachelor of Science — Emphasis: Data Analytics and Statistics (Utah Valley University, May 2025)",
  resumes: {
    full: "/resumes/Marty_Smithson_Resume_MASTER.pdf",
    measurement: "/resumes/Marty_Smithson_Resume_SCIENCE.pdf",
    systems: "/resumes/Marty_Smithson_Resume_OPERATOR.pdf",
  },
  keywords: [
    "Marketing Analytics & Measurement Lead",
    "marketing analytics",
    "marketing science",
    "media measurement",
    "marketing mix modeling",
    "MMM",
    "Google Meridian",
    "incrementality",
    "geo holdout",
    "RCT",
    "test-and-learn",
    "GeoLift",
    "synthetic control",
    "augmented synthetic control",
    "attribution",
    "MTA",
    "cash MER",
    "MER",
    "iROAS",
    "platform ROAS",
    "CAC",
    "LTV",
    "GTM analytics",
    "marketing data science",
    "decision science",
    "SQL",
    "Snowflake",
    "Python",
    "R",
    "dbt",
    "Looker",
    "Tableau",
    "BigQuery",
    "cohorts",
    "Cursor",
    "Claude",
    "ChatGPT",
    "AI-assisted analytics",
    "Google Cloud Run",
    "experimentation",
    "executive BI",
    "Oracle NetSuite",
  ],
} as const;

export const nav = [
  { href: "/work/desks", label: "Desks" },
  { href: "/work", label: "Work" },
  { href: "/resume", label: "Resume" },
] as const;
